{{- if or .Values.rbac.create .Values.iamServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    helm.sh/chart: {{ include "gcloud-sqlproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if and .Values.iamServiceAccount.create (not .Values.rbac.create) }}
{{- with .Values.iamServiceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
  name: {{ include "gcloud-sqlproxy.fullname" . }}
{{- end }}
