{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
  name: {{ include "gcloud-sqlproxy.fullname" . }}
{{- end }}
